### ISSUE TITLE
Submitting; Commit issue

### ISSUE THREAD

**Issue by knoxas** [MOLB7621/problem-set-3#42]
Hello,
I am trying to commit what I have for problem set 3. When I click on "commit" in the Git tab on R, this message pops up in a new window:

"*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <(NULL)>) not allowed"

I'm not able to type anything into the window, and I'm not sure how to access my git account from R. I thought I had used the SSH key in order to already be logged in to git, but I guess something else is going wrong.

Thanks,
Ashley

**Comment by jayhesselberth** [comment]
Not sure about that one. Can you bring it by office hours tomorrow? Or stop by my lab (RC1 South 10th floor) and maybe @mandylr or @lkwhite could help out?

**Comment by knoxas** [comment]
Hey Dr. Hesselberth,
I figured out the commit issue at least; if any one else is having an issue with this, I thought this page was helpful: https://www.r-bloggers.com/rstudio-and-github/
I already had the SSH key set up, but I still needed to open the Shell in R (Tools > Shell) and run these commands:
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

I'm going to go try to submit a pull request now - thank you!
-Ashley

**Comment by jayhesselberth** [comment]
Great, thanks for following up
